from __future__ import annotations

import argparse
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from minimal_adl.config import load_config
from minimal_adl.geometry import generate_perturbed_geometries, load_geometry, save_xyz, write_manifest
from minimal_adl.io_utils import ensure_dir


def main() -> None:
    parser = argparse.ArgumentParser(description="从种子结构生成一批初始几何。")
    parser.add_argument("--config", required=True, help="YAML 配置文件路径。")
    parser.add_argument("--num-samples", type=int, default=None, help="要生成的几何数量，默认读取配置文件。")
    parser.add_argument("--output-dir", default=None, help="几何输出目录，默认写入 data/raw/geometries。")
    parser.add_argument("--prefix", default="geom", help="样本名前缀。")
    args = parser.parse_args()

    config = load_config(args.config)
    sampling_cfg = config.get("sampling", {})
    num_samples = args.num_samples or int(sampling_cfg.get("default_pool_size", 400))
    output_dir = Path(args.output_dir) if args.output_dir else PROJECT_ROOT / "data" / "raw" / "geometries"
    output_dir = ensure_dir(output_dir)

    seed_geometry = load_geometry(config["paths"]["seed_geometry"])
    samples = generate_perturbed_geometries(
        seed=seed_geometry,
        num_samples=num_samples,
        displacement_std=float(sampling_cfg.get("displacement_std_angstrom", 0.08)),
        max_abs_displacement=float(sampling_cfg.get("max_abs_displacement_angstrom", 0.18)),
        rng_seed=int(sampling_cfg.get("random_seed", 20260324)),
        prefix=args.prefix,
    )

    manifest_entries = []
    for sample in samples:
        geometry_path = output_dir / f"{sample.sample_id}.xyz"
        save_xyz(sample, geometry_path, comment="generated by sample_initial_geometries.py")
        manifest_entries.append(sample.to_manifest_entry(geometry_path, PROJECT_ROOT))

    write_manifest(manifest_entries, config["paths"]["geometry_pool_manifest"])
    print(f"已生成 {len(samples)} 个几何，manifest 保存在 {config['paths']['geometry_pool_manifest']}")


if __name__ == "__main__":
    main()

